server:
  port: 10808
  host: 127.0.0.1

receiver:
  GR2:
    user:     scott
    password: tiger
    prefix_shootdate: 1

store:
  Local:
    base_dir: /storage/photos

  Flickr:
    key:        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    secret:     XXXXXXXXXXXXXXXX
    auth_token: XXXXXXXXXXXXXXXXX-XXXXXXXXXXXXXXXX
    tags:
      - doumeki
      - eye-fi
    is_public: 0
    is_friend: 0
    is_family: 1

  Ovi:
    username: XXXXXXXX
    password: XXXXXXXX

  Gallery2:
    url:      http://example.com/gr2/main.php
    username: scott
    password: tiger
    ignore_upload_photo_fail: 1

  Email:
    mail_from: hirose31@example.com
    mail_to:
      - XXXXXXXXXX@f.hatena.ne.jp
    mail_bcc:
      - XXXXXXXXXXX@photos.flickr.com
      - XXXXXXXXXXXXXXXXX@wassr.jp
    filename_in: body

notify:
  XMPP: # jabber.org
    jid: notifier@jabber.org
    password: XXXXXXXX
    to:
      - your_account@gmail.com
      - your_account2@jabber.org

# XMPP: # google talk
#   jid: notifier@gmail.com
#   password: XXXXXXXX
#   server_host: talk.google.com
#   tls: 1
#   to:
#     - your_account@gmail.com
#     - your_account2@jabber.org
